server:
  port: 8088
#
#bob
tsl:
  key-store:
    url: classpath:tls/client_keystore.jks
    password: client_keystore
    server-certificate:
      password: clientKey
  trust-store:
    url: classpath:tls/client_truststore.jks
    password: client_truststore