#server:
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/keystore.p12
#    key-store-password:

server:
  port: 8443
  ssl:
    enabled: true

    key-store: classpath:server_keystore.jks
    key-store-password: server_keystore
    key-password: serverKey
    key-alias: localhost

    trust-store: classpath:server_truststore.jks
    trust-store-password: server_truststore
    client-auth: need